const data = [
  {
    id: 14,
    title: 'MORTAL KOMBAT 11',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
    jumbo: true,
  },
  {
    id: 15,
    title: 'A BEAUTIFUL DAY IN THE NEIGHBORHOOD',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 16,
    title: 'PLAYSTATION',
    company: 'SONY',
    role: 'Edit + Motion Graphics',
    videos: ['a'],
  },
  {
    id: 17,
    title: 'DOWNTON ABBEY',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 18,
    title: 'SEVEN DEADLY SINS: GRAND CROSS',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 19,
    title: 'FOR LIFE',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a'],
  },
  {
    id: 20,
    title: 'KING OF FIGHTERS: ALL STARS',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 21,
    title: 'MAYANS MC',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 22,
    title: 'KOONGYA DRAW PARTY',
    company: '',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b'],
  },
  {
    id: 1,
    title: 'ASSASSINATION NATION',
    company: 'NEON',
    role: 'Cutdowns + Motion Graphics',
    videos: ['a', 'b', 'c'],
    jumbo: true,
  },
  {
    id: 4,
    title: 'SPIDER-MAN: HOMECOMING',
    company: 'SONY/MARVEL STUDIOS',
    role: 'Cutdowns + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 6,
    title: 'LOST IN SPACE',
    company: '20TH CENTURY FOX',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 7,
    title: 'WON\'T YOU BE MY NEIGHBOR?',
    company: 'FOCUS FEATURES',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 8,
    title: 'DREAMWORKS TROLLS',
    company: 'UNIVERSAL STUDIOS',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b'],
  },
  {
    id: 2,
    title: 'KINGDOM HEARTS 3',
    company: 'SQUARE ENIX',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b', 'c'],
  },
  {
    id: 10,
    title: 'OCTOPATH TRAVELER',
    company: 'SQUARE ENIX',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b'],
  },
  {
    id: 11,
    title: 'X-MEN: TRILOGY',
    company: '20TH CENTURY FOX',
    role: 'Edit + Motion Graphics',
    videos: ['a', 'b'],
    jumbo: true,
  },
  {
    id: 3,
    title: 'RAINBOW SIX: SIEGE',
    company: 'UBISOFT',
    role: 'Edit + Motion Graphics',
    videos: ['a'],
  },
];

export default data;